/**
 * Resilient Healthcare Data Store for MediBridge LK
 * Seamlessly services the entire platform with full Sri Lankan medical data,
 * NMRA price records, pharmacy feeds, and safety alerts.
 */

export interface MedicineRecord {
  _id: string;
  brand_name: string;
  generic_name: string;
  active_ingredient: string;
  strength: string;
  strength_value: number;
  strength_unit: string;
  dosage_form: string;
  manufacturer: string;
  pack_size: string;
  pack_units: number;
  country: string;
  regulatory_status: string;
  nmra_reg_no: string;
  category: string;
  source: string;
  verified: boolean;
  patient_explanation: {
    what_is_it: string;
    common_uses: string[];
    important_info: string;
    precautions: string[];
  };
}

export interface PriceRecord {
  _id: string;
  medicine_id: string;
  pharmacy_id?: string;
  pharmacy_name: string;
  price: number;
  unit_price: number;
  currency: string;
  price_type: 'NMRA_MRP' | 'PHARMACY_SELLING_PRICE' | 'PARTNER_PRICE' | 'ESTIMATED_PRICE';
  effective_from: Date;
  effective_to: Date | null;
  source: string;
  verified_at: Date;
  availability: 'IN_STOCK' | 'LOW_STOCK' | 'OUT_OF_STOCK' | 'UNKNOWN';
}

export interface PharmacyRecord {
  _id: string;
  name: string;
  chain: string;
  license_number: string;
  address: string;
  district: string;
  city: string;
  phone: string;
  email: string;
  website: string;
  verified: boolean;
  provides_api: boolean;
  opening_hours: string;
  available_medicines_count?: number;
}

export interface SafetyAlertRecord {
  _id: string;
  medicine_name: string;
  generic_name?: string;
  batch_number?: string;
  alert_type: 'RECALL' | 'REVOCATION' | 'QUALITY_SAFETY' | 'PRICE_CEILING' | 'ADVISORY';
  severity: 'CRITICAL' | 'HIGH' | 'MEDIUM' | 'LOW';
  source: string;
  description: string;
  action_required: string;
  published_at: Date;
  active: boolean;
}

const PAST_3M = new Date(Date.now() - 90 * 24 * 60 * 60 * 1000);
const PAST_6M = new Date(Date.now() - 180 * 24 * 60 * 60 * 1000);

export const INITIAL_PHARMACIES: PharmacyRecord[] = [
  {
    _id: 'pharma-01',
    name: 'State Pharmaceuticals Corporation (Rajya Osu Sala)',
    chain: 'SPC Sri Lanka',
    license_number: 'NMRA/PH/COL-001',
    address: 'No. 255, Dharmapala Mawatha, Town Hall',
    district: 'Colombo',
    city: 'Colombo 07',
    phone: '+94 11 269 4965',
    email: 'osusala.townhall@spc.lk',
    website: 'https://spc.lk',
    verified: true,
    provides_api: true,
    opening_hours: '24 Hours Open',
    available_medicines_count: 54,
  },
  {
    _id: 'pharma-02',
    name: 'Healthguard Pharmacy (Bambalapitiya)',
    chain: 'Healthguard (Sunshine Holdings)',
    license_number: 'NMRA/PH/COL-042',
    address: 'No. 502, Galle Road, Bambalapitiya',
    district: 'Colombo',
    city: 'Colombo 04',
    phone: '+94 11 470 1200',
    email: 'support@healthguard.lk',
    website: 'https://healthguard.lk',
    verified: true,
    provides_api: true,
    opening_hours: '7:30 AM - 11:00 PM',
    available_medicines_count: 62,
  },
  {
    _id: 'pharma-03',
    name: 'Nawaloka Medicare Pharmacy',
    chain: 'Nawaloka Hospitals',
    license_number: 'NMRA/PH/COL-088',
    address: 'No. 23, Deshamanya H.K. Dharmadasa Mawatha',
    district: 'Colombo',
    city: 'Colombo 02',
    phone: '+94 11 557 7111',
    email: 'pharmacy@nawaloka.com',
    website: 'https://nawaloka.com',
    verified: true,
    provides_api: false,
    opening_hours: '24 Hours Open',
    available_medicines_count: 48,
  },
  {
    _id: 'pharma-04',
    name: 'Asiri Central Pharmacy',
    chain: 'Asiri Health',
    license_number: 'NMRA/PH/COL-114',
    address: 'No. 114, Norris Canal Road',
    district: 'Colombo',
    city: 'Colombo 10',
    phone: '+94 11 466 5500',
    email: 'pharmacy@asiri.lk',
    website: 'https://asirihealth.com',
    verified: true,
    provides_api: true,
    opening_hours: '24 Hours Open',
    available_medicines_count: 50,
  },
  {
    _id: 'pharma-05',
    name: 'Rajya Osu Sala (Kandy City)',
    chain: 'SPC Sri Lanka',
    license_number: 'NMRA/PH/KDY-012',
    address: 'No. 82, Dalada Veediya',
    district: 'Kandy',
    city: 'Kandy',
    phone: '+94 81 222 3450',
    email: 'osusala.kandy@spc.lk',
    website: 'https://spc.lk',
    verified: true,
    provides_api: true,
    opening_hours: '8:00 AM - 9:00 PM',
    available_medicines_count: 45,
  },
];

export const INITIAL_MEDICINES: MedicineRecord[] = [
  {
    _id: 'med-01',
    brand_name: 'Panadol',
    generic_name: 'Paracetamol',
    active_ingredient: 'Paracetamol',
    strength: '500 mg',
    strength_value: 500,
    strength_unit: 'mg',
    dosage_form: 'Tablet',
    manufacturer: 'GlaxoSmithKline (GSK) Sri Lanka',
    pack_size: '10 Tablets (Strip)',
    pack_units: 10,
    country: 'Sri Lanka',
    regulatory_status: 'NMRA_REGISTERED',
    nmra_reg_no: 'NMRA-DR-0491',
    category: 'Analgesics & Pain Relief',
    source: 'NMRA Gazette 2341/39',
    verified: true,
    patient_explanation: {
      what_is_it: 'Panadol is a common pain reliever and fever reducer containing Paracetamol.',
      common_uses: ['Headaches and migraines', 'Fever and body aches', 'Toothaches and mild muscle pain'],
      important_info: 'Take 1 to 2 tablets every 4 to 6 hours as needed. Do not exceed 8 tablets (4000 mg) in 24 hours.',
      precautions: [
        'Do not combine with other cold or flu medicines that also contain Paracetamol.',
        'Excessive use can cause severe liver injury.',
        'Consult your doctor if fever lasts more than 3 days.',
      ],
    },
  },
  {
    _id: 'med-02',
    brand_name: 'ParaLanka (SPC Generic)',
    generic_name: 'Paracetamol',
    active_ingredient: 'Paracetamol',
    strength: '500 mg',
    strength_value: 500,
    strength_unit: 'mg',
    dosage_form: 'Tablet',
    manufacturer: 'State Pharmaceuticals Manufacturing Corporation (SPMC)',
    pack_size: '10 Tablets (Strip)',
    pack_units: 10,
    country: 'Sri Lanka',
    regulatory_status: 'NMRA_VERIFIED',
    nmra_reg_no: 'NMRA-SPMC-0012',
    category: 'Analgesics & Pain Relief',
    source: 'SPMC Ratmalana / NMRA',
    verified: true,
    patient_explanation: {
      what_is_it: 'ParaLanka is the state-manufactured generic Paracetamol tablet produced in Ratmalana, Sri Lanka.',
      common_uses: ['Fever reduction', 'Mild to moderate body pain', 'Headache relief'],
      important_info: 'Exact bioequivalent active ingredient (Paracetamol 500mg) at public-sector subsidized pricing.',
      precautions: ['Do not exceed 8 tablets daily.', 'Avoid alcohol consumption while taking this medicine.'],
    },
  },
  {
    _id: 'med-03',
    brand_name: 'Calpol 500',
    generic_name: 'Paracetamol',
    active_ingredient: 'Paracetamol',
    strength: '500 mg',
    strength_value: 500,
    strength_unit: 'mg',
    dosage_form: 'Tablet',
    manufacturer: 'GlaxoSmithKline Pharmaceuticals',
    pack_size: '10 Tablets (Strip)',
    pack_units: 10,
    country: 'Sri Lanka',
    regulatory_status: 'NMRA_REGISTERED',
    nmra_reg_no: 'NMRA-DR-1092',
    category: 'Analgesics & Pain Relief',
    source: 'NMRA Database',
    verified: true,
    patient_explanation: {
      what_is_it: 'Calpol 500 is a fast-acting Paracetamol tablet used to relieve fever and pain.',
      common_uses: ['Fever', 'Sore throat pain', 'Post-vaccination pain'],
      important_info: 'Take with or without food with water.',
      precautions: ['Check other medications for Paracetamol content.'],
    },
  },
  {
    _id: 'med-04',
    brand_name: 'Amoxil 500',
    generic_name: 'Amoxicillin',
    active_ingredient: 'Amoxicillin',
    strength: '500 mg',
    strength_value: 500,
    strength_unit: 'mg',
    dosage_form: 'Capsule',
    manufacturer: 'GlaxoSmithKline (GSK)',
    pack_size: '10 Capsules',
    pack_units: 10,
    country: 'United Kingdom',
    regulatory_status: 'NMRA_REGISTERED',
    nmra_reg_no: 'NMRA-DR-0211',
    category: 'Antibiotics',
    source: 'NMRA Gazette 2341/39',
    verified: true,
    patient_explanation: {
      what_is_it: 'Amoxil is an original brand penicillin-type antibiotic used to treat bacterial infections.',
      common_uses: ['Chest infections (bronchitis, pneumonia)', 'Throat and ear infections', 'Urinary tract infections'],
      important_info: 'Complete the entire prescribed course even if symptoms disappear after a few days.',
      precautions: [
        'Do not take if you have a known allergy to penicillin.',
        'Does not work against viral infections like common cold or flu.',
      ],
    },
  },
  {
    _id: 'med-05',
    brand_name: 'Amoxicillin SPMC',
    generic_name: 'Amoxicillin',
    active_ingredient: 'Amoxicillin',
    strength: '500 mg',
    strength_value: 500,
    strength_unit: 'mg',
    dosage_form: 'Capsule',
    manufacturer: 'State Pharmaceuticals Manufacturing Corporation (SPMC)',
    pack_size: '10 Capsules',
    pack_units: 10,
    country: 'Sri Lanka',
    regulatory_status: 'NMRA_VERIFIED',
    nmra_reg_no: 'NMRA-SPMC-0044',
    category: 'Antibiotics',
    source: 'NMRA Gazette 2341/39',
    verified: true,
    patient_explanation: {
      what_is_it: 'Certified generic Amoxicillin capsule containing identical 500 mg active ingredient.',
      common_uses: ['Bacterial respiratory infections', 'Skin infections', 'Dental infections'],
      important_info: 'Take with food to minimize stomach upset. Complete full regimen.',
      precautions: ['Stop immediately and seek emergency care if allergic rash or facial swelling develops.'],
    },
  },
  {
    _id: 'med-06',
    brand_name: 'Lipitor 20',
    generic_name: 'Atorvastatin',
    active_ingredient: 'Atorvastatin',
    strength: '20 mg',
    strength_value: 20,
    strength_unit: 'mg',
    dosage_form: 'Tablet',
    manufacturer: 'Pfizer Pharmaceuticals',
    pack_size: '30 Tablets',
    pack_units: 30,
    country: 'Ireland',
    regulatory_status: 'NMRA_REGISTERED',
    nmra_reg_no: 'NMRA-DR-3312',
    category: 'Cardiovascular & Cholesterol',
    source: 'NMRA Gazette 2341/39',
    verified: true,
    patient_explanation: {
      what_is_it: 'Lipitor is a statin medication that lowers bad cholesterol (LDL) and triglycerides in blood.',
      common_uses: ['Preventing heart attacks and strokes', 'Hypercholesterolemia management'],
      important_info: 'Usually taken once daily at bedtime with or without food.',
      precautions: [
        'Notify doctor immediately if you experience unexplained muscle pain, tenderness, or weakness.',
        'Avoid consuming large quantities of grapefruit juice.',
      ],
    },
  },
  {
    _id: 'med-07',
    brand_name: 'Atorva 20',
    generic_name: 'Atorvastatin',
    active_ingredient: 'Atorvastatin',
    strength: '20 mg',
    strength_value: 20,
    strength_unit: 'mg',
    dosage_form: 'Tablet',
    manufacturer: 'Zydus Cadila',
    pack_size: '30 Tablets',
    pack_units: 30,
    country: 'India',
    regulatory_status: 'NMRA_REGISTERED',
    nmra_reg_no: 'NMRA-DR-4105',
    category: 'Cardiovascular & Cholesterol',
    source: 'NMRA Gazette 2341/39',
    verified: true,
    patient_explanation: {
      what_is_it: 'Atorva 20 is an NMRA-approved bioequivalent generic of Atorvastatin.',
      common_uses: ['Lowering high cholesterol', 'Cardiovascular risk reduction'],
      important_info: 'Takes several weeks of consistent usage to reach full lipid-lowering efficacy.',
      precautions: ['Periodic liver enzyme monitoring may be advised by your physician.'],
    },
  },
  {
    _id: 'med-08',
    brand_name: 'Storvas 20',
    generic_name: 'Atorvastatin',
    active_ingredient: 'Atorvastatin',
    strength: '20 mg',
    strength_value: 20,
    strength_unit: 'mg',
    dosage_form: 'Tablet',
    manufacturer: 'Sun Pharmaceutical Industries',
    pack_size: '30 Tablets',
    pack_units: 30,
    country: 'India',
    regulatory_status: 'NMRA_REGISTERED',
    nmra_reg_no: 'NMRA-DR-2201',
    category: 'Cardiovascular & Cholesterol',
    source: 'NMRA Gazette',
    verified: true,
    patient_explanation: {
      what_is_it: 'Storvas 20 contains 20mg of Atorvastatin calcium.',
      common_uses: ['Atherosclerosis prevention', 'Cholesterol management'],
      important_info: 'Take regularly at the same time each day.',
      precautions: ['Do not stop taking without consulting your physician.'],
    },
  },
  {
    _id: 'med-09',
    brand_name: 'Glucophage 500',
    generic_name: 'Metformin Hydrochloride',
    active_ingredient: 'Metformin',
    strength: '500 mg',
    strength_value: 500,
    strength_unit: 'mg',
    dosage_form: 'Tablet',
    manufacturer: 'Merck Healthcare',
    pack_size: '100 Tablets',
    pack_units: 100,
    country: 'France',
    regulatory_status: 'NMRA_REGISTERED',
    nmra_reg_no: 'NMRA-DR-0814',
    category: 'Antidiabetics',
    source: 'NMRA Gazette 2341/39',
    verified: true,
    patient_explanation: {
      what_is_it: 'Glucophage is the leading brand of Metformin used to manage Type 2 Diabetes.',
      common_uses: ['Controlling blood sugar in Type 2 diabetes', 'PCOS insulin sensitivity'],
      important_info: 'Always take with or directly after a meal to reduce nausea and stomach upset.',
      precautions: ['Stay well hydrated.', 'Do not skip meals.'],
    },
  },
  {
    _id: 'med-10',
    brand_name: 'Metformin SPMC 500',
    generic_name: 'Metformin Hydrochloride',
    active_ingredient: 'Metformin',
    strength: '500 mg',
    strength_value: 500,
    strength_unit: 'mg',
    dosage_form: 'Tablet',
    manufacturer: 'State Pharmaceuticals Manufacturing Corporation (SPMC)',
    pack_size: '100 Tablets',
    pack_units: 100,
    country: 'Sri Lanka',
    regulatory_status: 'NMRA_VERIFIED',
    nmra_reg_no: 'NMRA-SPMC-0028',
    category: 'Antidiabetics',
    source: 'NMRA Gazette 2341/39',
    verified: true,
    patient_explanation: {
      what_is_it: 'National generic Metformin manufactured locally under strict quality standards.',
      common_uses: ['Type 2 diabetes glycemic control'],
      important_info: 'Identical 500mg active molecule providing high affordability for lifelong diabetes care.',
      precautions: ['Inform your doctor before any X-ray scan involving contrast dye.'],
    },
  },
  {
    _id: 'med-11',
    brand_name: 'Losec 20',
    generic_name: 'Omeprazole',
    active_ingredient: 'Omeprazole',
    strength: '20 mg',
    strength_value: 20,
    strength_unit: 'mg',
    dosage_form: 'Capsule',
    manufacturer: 'AstraZeneca',
    pack_size: '14 Capsules',
    pack_units: 14,
    country: 'Sweden',
    regulatory_status: 'NMRA_REGISTERED',
    nmra_reg_no: 'NMRA-DR-0105',
    category: 'Gastrointestinal & Antacids',
    source: 'NMRA Gazette 2341/39',
    verified: true,
    patient_explanation: {
      what_is_it: 'Losec is a proton pump inhibitor (PPI) that decreases stomach acid.',
      common_uses: ['Gastric ulcers', 'Acid reflux (GERD)', 'Stomach protection'],
      important_info: 'Swallow whole with water 30 to 60 minutes before morning breakfast.',
      precautions: ['Long-term daily use should be reviewed regularly by your doctor.'],
    },
  },
  {
    _id: 'med-12',
    brand_name: 'Omez 20',
    generic_name: 'Omeprazole',
    active_ingredient: 'Omeprazole',
    strength: '20 mg',
    strength_value: 20,
    strength_unit: 'mg',
    dosage_form: 'Capsule',
    manufacturer: "Dr. Reddy's Laboratories",
    pack_size: '14 Capsules',
    pack_units: 14,
    country: 'India',
    regulatory_status: 'NMRA_REGISTERED',
    nmra_reg_no: 'NMRA-DR-1550',
    category: 'Gastrointestinal & Antacids',
    source: 'NMRA Gazette 2341/39',
    verified: true,
    patient_explanation: {
      what_is_it: 'Omez is a widely trusted, affordable generic Omeprazole capsule.',
      common_uses: ['Heartburn', 'Gastric hyperacidity', 'Peptic ulcer prevention'],
      important_info: 'Take once daily before food.',
      precautions: ['Keep in a cool, moisture-free place.'],
    },
  },
  {
    _id: 'med-13',
    brand_name: 'Ventolin Evohaler 100mcg',
    generic_name: 'Salbutamol',
    active_ingredient: 'Salbutamol',
    strength: '100 mcg/dose',
    strength_value: 100,
    strength_unit: 'mcg',
    dosage_form: 'Inhaler',
    manufacturer: 'Glaxo Wellcome / GSK',
    pack_size: '200 Doses Canister',
    pack_units: 200,
    country: 'France',
    regulatory_status: 'NMRA_REGISTERED',
    nmra_reg_no: 'NMRA-DR-0033',
    category: 'Respiratory',
    source: 'NMRA Gazette 2341/39',
    verified: true,
    patient_explanation: {
      what_is_it: 'Ventolin is a fast-acting bronchodilator reliever inhaler for asthma and wheezing.',
      common_uses: ['Relieving sudden shortness of breath and wheezing', 'Exercise-induced bronchospasm'],
      important_info: '1 to 2 puffs when experiencing acute wheezing.',
      precautions: ['If needing more than 3-4 times a day, seek medical review immediately.'],
    },
  },
  {
    _id: 'med-14',
    brand_name: 'Asthalin 100 Inhaler',
    generic_name: 'Salbutamol',
    active_ingredient: 'Salbutamol',
    strength: '100 mcg/dose',
    strength_value: 100,
    strength_unit: 'mcg',
    dosage_form: 'Inhaler',
    manufacturer: 'Cipla Limited',
    pack_size: '200 Doses Canister',
    pack_units: 200,
    country: 'India',
    regulatory_status: 'NMRA_REGISTERED',
    nmra_reg_no: 'NMRA-DR-0988',
    category: 'Respiratory',
    source: 'NMRA Gazette 2341/39',
    verified: true,
    patient_explanation: {
      what_is_it: 'Cost-effective generic Salbutamol aerosol inhaler by Cipla.',
      common_uses: ['Bronchospasm relief', 'Asthma symptom management'],
      important_info: 'Shake well before each actuation.',
      precautions: ['Keep away from direct heat and sunlight.'],
    },
  },
];

export const INITIAL_PRICES: PriceRecord[] = [
  // Panadol (Historical 6M ago, closed 3M ago)
  {
    _id: 'price-p01',
    medicine_id: 'med-01',
    pharmacy_name: 'NMRA Sri Lanka Gazette',
    price: 38.0,
    unit_price: 3.8,
    currency: 'LKR',
    price_type: 'NMRA_MRP',
    effective_from: PAST_6M,
    effective_to: PAST_3M,
    source: 'Gazette Extraordinary 2291/44',
    verified_at: PAST_6M,
    availability: 'IN_STOCK',
  },
  // Panadol (Current Active)
  {
    _id: 'price-p02',
    medicine_id: 'med-01',
    pharmacy_name: 'NMRA Sri Lanka Gazette',
    price: 45.0,
    unit_price: 4.5,
    currency: 'LKR',
    price_type: 'NMRA_MRP',
    effective_from: PAST_3M,
    effective_to: null,
    source: 'Gazette Extraordinary 2341/39',
    verified_at: PAST_3M,
    availability: 'IN_STOCK',
  },
  {
    _id: 'price-p03',
    medicine_id: 'med-01',
    pharmacy_id: 'pharma-02',
    pharmacy_name: 'Healthguard Pharmacy (Bambalapitiya)',
    price: 44.5,
    unit_price: 4.45,
    currency: 'LKR',
    price_type: 'PHARMACY_SELLING_PRICE',
    effective_from: PAST_3M,
    effective_to: null,
    source: 'Healthguard POS Integration',
    verified_at: PAST_3M,
    availability: 'IN_STOCK',
  },
  {
    _id: 'price-p04',
    medicine_id: 'med-01',
    pharmacy_id: 'pharma-04',
    pharmacy_name: 'Asiri Central Pharmacy',
    price: 45.0,
    unit_price: 4.5,
    currency: 'LKR',
    price_type: 'PHARMACY_SELLING_PRICE',
    effective_from: PAST_3M,
    effective_to: null,
    source: 'Asiri Pharmacy System',
    verified_at: PAST_3M,
    availability: 'IN_STOCK',
  },

  // ParaLanka (SPC Generic)
  {
    _id: 'price-p05',
    medicine_id: 'med-02',
    pharmacy_id: 'pharma-01',
    pharmacy_name: 'State Pharmaceuticals Corporation (Rajya Osu Sala)',
    price: 22.0,
    unit_price: 2.2,
    currency: 'LKR',
    price_type: 'PHARMACY_SELLING_PRICE',
    effective_from: PAST_3M,
    effective_to: null,
    source: 'SPC Rajya Osu Sala Retail Price List',
    verified_at: PAST_3M,
    availability: 'IN_STOCK',
  },
  {
    _id: 'price-p06',
    medicine_id: 'med-02',
    pharmacy_name: 'NMRA Sri Lanka Gazette',
    price: 25.0,
    unit_price: 2.5,
    currency: 'LKR',
    price_type: 'NMRA_MRP',
    effective_from: PAST_3M,
    effective_to: null,
    source: 'NMRA Gazette 2341/39',
    verified_at: PAST_3M,
    availability: 'IN_STOCK',
  },

  // Calpol
  {
    _id: 'price-p07',
    medicine_id: 'med-03',
    pharmacy_id: 'pharma-03',
    pharmacy_name: 'Nawaloka Medicare Pharmacy',
    price: 36.0,
    unit_price: 3.6,
    currency: 'LKR',
    price_type: 'PHARMACY_SELLING_PRICE',
    effective_from: PAST_3M,
    effective_to: null,
    source: 'Nawaloka POS Feed',
    verified_at: PAST_3M,
    availability: 'IN_STOCK',
  },

  // Amoxil 500
  {
    _id: 'price-p08',
    medicine_id: 'med-04',
    pharmacy_name: 'NMRA Sri Lanka Gazette',
    price: 480.0,
    unit_price: 48.0,
    currency: 'LKR',
    price_type: 'NMRA_MRP',
    effective_from: PAST_6M,
    effective_to: null,
    source: 'NMRA Gazette 2341/39',
    verified_at: PAST_6M,
    availability: 'IN_STOCK',
  },
  {
    _id: 'price-p09',
    medicine_id: 'med-04',
    pharmacy_id: 'pharma-02',
    pharmacy_name: 'Healthguard Pharmacy (Bambalapitiya)',
    price: 470.0,
    unit_price: 47.0,
    currency: 'LKR',
    price_type: 'PHARMACY_SELLING_PRICE',
    effective_from: PAST_3M,
    effective_to: null,
    source: 'Healthguard POS Integration',
    verified_at: PAST_3M,
    availability: 'IN_STOCK',
  },
  // Amoxicillin SPMC
  {
    _id: 'price-p10',
    medicine_id: 'med-05',
    pharmacy_id: 'pharma-01',
    pharmacy_name: 'State Pharmaceuticals Corporation (Rajya Osu Sala)',
    price: 240.0,
    unit_price: 24.0,
    currency: 'LKR',
    price_type: 'PHARMACY_SELLING_PRICE',
    effective_from: PAST_3M,
    effective_to: null,
    source: 'SPC Rajya Osu Sala Price List',
    verified_at: PAST_3M,
    availability: 'IN_STOCK',
  },

  // Lipitor 20
  {
    _id: 'price-p11',
    medicine_id: 'med-06',
    pharmacy_name: 'NMRA Sri Lanka Gazette',
    price: 3600.0,
    unit_price: 120.0,
    currency: 'LKR',
    price_type: 'NMRA_MRP',
    effective_from: PAST_3M,
    effective_to: null,
    source: 'NMRA Gazette 2341/39',
    verified_at: PAST_3M,
    availability: 'IN_STOCK',
  },
  {
    _id: 'price-p12',
    medicine_id: 'med-06',
    pharmacy_id: 'pharma-02',
    pharmacy_name: 'Healthguard Pharmacy (Bambalapitiya)',
    price: 3450.0,
    unit_price: 115.0,
    currency: 'LKR',
    price_type: 'PHARMACY_SELLING_PRICE',
    effective_from: PAST_3M,
    effective_to: null,
    source: 'Healthguard POS Integration',
    verified_at: PAST_3M,
    availability: 'IN_STOCK',
  },
  // Atorva 20
  {
    _id: 'price-p13',
    medicine_id: 'med-07',
    pharmacy_id: 'pharma-03',
    pharmacy_name: 'Nawaloka Medicare Pharmacy',
    price: 1650.0,
    unit_price: 55.0,
    currency: 'LKR',
    price_type: 'PHARMACY_SELLING_PRICE',
    effective_from: PAST_3M,
    effective_to: null,
    source: 'Nawaloka Pharmacy Feed',
    verified_at: PAST_3M,
    availability: 'IN_STOCK',
  },
  // Storvas 20
  {
    _id: 'price-p14',
    medicine_id: 'med-08',
    pharmacy_id: 'pharma-01',
    pharmacy_name: 'State Pharmaceuticals Corporation (Rajya Osu Sala)',
    price: 1350.0,
    unit_price: 45.0,
    currency: 'LKR',
    price_type: 'PHARMACY_SELLING_PRICE',
    effective_from: PAST_3M,
    effective_to: null,
    source: 'SPC Retail Price Master',
    verified_at: PAST_3M,
    availability: 'IN_STOCK',
  },

  // Glucophage 500 vs Metformin SPMC
  {
    _id: 'price-p15',
    medicine_id: 'med-09',
    pharmacy_name: 'NMRA Sri Lanka Gazette',
    price: 1950.0,
    unit_price: 19.5,
    currency: 'LKR',
    price_type: 'NMRA_MRP',
    effective_from: PAST_3M,
    effective_to: null,
    source: 'NMRA Gazette 2341/39',
    verified_at: PAST_3M,
    availability: 'IN_STOCK',
  },
  {
    _id: 'price-p16',
    medicine_id: 'med-10',
    pharmacy_id: 'pharma-01',
    pharmacy_name: 'State Pharmaceuticals Corporation (Rajya Osu Sala)',
    price: 650.0,
    unit_price: 6.5,
    currency: 'LKR',
    price_type: 'PHARMACY_SELLING_PRICE',
    effective_from: PAST_3M,
    effective_to: null,
    source: 'SPC Price Gazette',
    verified_at: PAST_3M,
    availability: 'IN_STOCK',
  },

  // Losec 20 vs Omez 20
  {
    _id: 'price-p17',
    medicine_id: 'med-11',
    pharmacy_name: 'NMRA Sri Lanka Gazette',
    price: 1400.0,
    unit_price: 100.0,
    currency: 'LKR',
    price_type: 'NMRA_MRP',
    effective_from: PAST_3M,
    effective_to: null,
    source: 'NMRA Gazette 2341/39',
    verified_at: PAST_3M,
    availability: 'IN_STOCK',
  },
  {
    _id: 'price-p18',
    medicine_id: 'med-12',
    pharmacy_id: 'pharma-01',
    pharmacy_name: 'State Pharmaceuticals Corporation (Rajya Osu Sala)',
    price: 350.0,
    unit_price: 25.0,
    currency: 'LKR',
    price_type: 'PHARMACY_SELLING_PRICE',
    effective_from: PAST_3M,
    effective_to: null,
    source: 'SPC Price List',
    verified_at: PAST_3M,
    availability: 'IN_STOCK',
  },

  // Ventolin vs Asthalin
  {
    _id: 'price-p19',
    medicine_id: 'med-13',
    pharmacy_name: 'NMRA Sri Lanka Gazette',
    price: 1250.0,
    unit_price: 6.25,
    currency: 'LKR',
    price_type: 'NMRA_MRP',
    effective_from: PAST_3M,
    effective_to: null,
    source: 'NMRA Gazette 2341/39',
    verified_at: PAST_3M,
    availability: 'IN_STOCK',
  },
  {
    _id: 'price-p20',
    medicine_id: 'med-14',
    pharmacy_id: 'pharma-01',
    pharmacy_name: 'State Pharmaceuticals Corporation (Rajya Osu Sala)',
    price: 680.0,
    unit_price: 3.4,
    currency: 'LKR',
    price_type: 'PHARMACY_SELLING_PRICE',
    effective_from: PAST_3M,
    effective_to: null,
    source: 'SPC Price Master',
    verified_at: PAST_3M,
    availability: 'IN_STOCK',
  },
];

export const INITIAL_SAFETY_ALERTS: SafetyAlertRecord[] = [
  {
    _id: 'alert-01',
    medicine_name: 'Guanfacine HCl 1mg Tablets',
    generic_name: 'Guanfacine',
    batch_number: 'BATCH-LK-2025-091',
    alert_type: 'RECALL',
    severity: 'CRITICAL',
    source: 'NMRA National Medicines Quality Assurance Laboratory (NMQAL)',
    description:
      'Immediate recall of Batch LK-2025-091 due to out-of-specification dissolution profile detected during post-market surveillance.',
    action_required:
      'Pharmacies must quarantine stock immediately. Patients holding this batch should return it to the dispensing pharmacy for a safe replacement.',
    published_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    active: true,
  },
  {
    _id: 'alert-02',
    medicine_name: 'Ceftriaxone 1g Injection',
    generic_name: 'Ceftriaxone Sodium',
    batch_number: 'CF-99214',
    alert_type: 'REVOCATION',
    severity: 'HIGH',
    source: 'NMRA Enforcement Division',
    description:
      'Provisional registration revoked following failure to comply with Current Good Manufacturing Practices (cGMP) audit standards.',
    action_required: 'Hospitals and pharmacies must cease dispensing product under registration NMRA-DR-9921.',
    published_at: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000),
    active: true,
  },
  {
    _id: 'alert-03',
    medicine_name: 'Paracetamol Paediatric Oral Suspension 120mg/5ml',
    generic_name: 'Paracetamol',
    batch_number: 'All batches from manufacturer X',
    alert_type: 'QUALITY_SAFETY',
    severity: 'HIGH',
    source: 'Ministry of Health & NMRA Joint Advisory',
    description:
      'Mandatory screening for Diethylene Glycol (DEG) and Ethylene Glycol (EG) contaminants in liquid oral formulations.',
    action_required:
      'All importers and manufacturers must provide accredited certificates of analysis confirming absence of DEG and EG prior to retail distribution.',
    published_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000),
    active: true,
  },
];
